version: "3.8"
services:
  client:
    container_name: 'matcha_client'
    build: ./client/
    volumes:
      - "./client:/client"
    working_dir: "/client"
    entrypoint: "/bin/bash -c"
    command:
      - "npm run dev"
    ports:
      - 3000:3000
    environment:
        API_URL: http://localhost:4000

  server:
    container_name: 'matcha_server'
    build: ./server/
    depends_on:
      - mariadb
    volumes:
      - ./server:/server
    working_dir: "/server"
    environment:
        SERVER_TOKEN: RandomServerTokenSecret
        REFRESH_TOKEN: RandomRefreshTokenSecret
        MYSQL_HOST: mariadb
        MYSQL_DATABASE: matcha
        MYSQL_USER: matcha
        MYSQL_ROOT_PASSWORD: RandomRootPassword
        MYSQL_PASSWORD: RandomPassword
        MYSQL_CONNECTION_LIMIT: 5
        DOMAIN_NAME: localhost
        PORT: 4000
        PROTOCOL: http
        CLIENT_URL: http://localhost:3000
        IMG_PATH: "/server/images/"
        ADMIN_EMAIL: admins.email@address.com
        ## Must give these for email verification to work
        MAIL_USER: your.outlook.email@address.com
        OUTLOOK_PASSWORD: yourOutlookPassword
    entrypoint: "/bin/bash -c"
    command:
      - "npm start"
    ports:
      - 4000:4000
  mariadb:
    image: 'mariadb'
    container_name: 'matcha_db'
    working_dir: /server
    volumes:
        - mariadb-data:/var/lib/mysql
        - ./config/db/init.sql:/server/config/init.sql
        - ./config/db/my.cnf:/etc/mysql/my.cnf
    command: --init-file /server/config/init.sql
    environment:
        MYSQL_DATABASE: matcha
        MYSQL_USER: matcha
        MYSQL_ROOT_PASSWORD: RandomRootPassword
        MYSQL_PASSWORD: RandomPassword
    ports:
        - '8083:3306'
    restart: always

  phpmyadmin:
      depends_on:
          - mariadb
      image: phpmyadmin
      container_name: 'phpmyadmin'
      ports:
          - 8081:80
      environment:
          PMA_HOST: mariadb
volumes:
    mariadb-data:
        name: matcha-data

# Launch with:
#   make production
# Create dummy users with:
#   make users