USE matcha;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS photos;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS tokens;
